---
title: "Statistics Review"
subtitle: "EC 320, Set 02"
author: Andrew Dickinson
date: last-modified
date-format: "Spring YYYY"
format: 
  revealjs:
    theme: [default, ../styles.scss]
    monobackgroundcolor: #F5F5F5
    slide-number: true
    footer: "EC320, Set 02 | Statistics Review"
    preview-links: auto
    code-fold: FALSE
    code-copy: TRUE
    highlight-style: a11y-light
    cache: TRUE
    # html-math-method: mathjax 
title-slide-attributes: 
  data-background-position: left
hideFootnotes: true
---

# Prologue{.inverse .note}


```{r}
pacman::p_load(hrbrthemes, fastverse, tidyverse, magrittr, wooldridge, here, kableExtra, nord, latex2exp)


hi = nord_palettes$polarnight[3]
hii = nord_palettes$frost[3] 
hp = nord_palettes$aurora[5]
higreen = nord_palettes$aurora[4]
hiorange = nord_palettes$aurora[2]
hired = nord_palettes$aurora[1]

mytheme = theme_ipsum(base_family = "Fira Sans Book", base_size = 20) +
 theme(panel.grid.minor.x = element_blank(),
       axis.title.x = element_text(size = 28),
       axis.title.y = element_text(size = 28))

mytheme_s = mytheme + 
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.line = element_line(color = hi))
```

::: {.hidden}
$$
\usepackage{amsmath}
$$
:::

{{< include _011-prologue.qmd >}}

# Notation {.inverse .note}

{{< include _012-notation.qmd >}}

# Basic probability {.inverse .note}

{{< include _013-probability.qmd >}}

# Distributions {.inverse .note}

{{< include _014-distros.qmd >}}

# Moments {.inverse .note}

{{< include _015-moments.qmd >}}

# Estimators {.inverse .note}

{{< include _016-estimators.qmd >}}

# Sampling {.inverse .note}
{{< include _017-sampling.qmd >}}

# Hypothesis testing {.inverse .note}

{{< include _019-hytesting.qmd >}}

# Data types {.inverse .note}

{{< include _018-data.qmd >}}

```{r}
#| include: false
#| eval: false
#| echo: false

renderthis::to_pdf(from = "./slides/001-review/010-main.html", to = "./slides/001-review/010-main.pdf")
```

<!--

Notes:

- Move hypothesis testing to the second linear regression lecture
-

 -->