---
name: distros
---

---

## Distributions

> Function that represents all outcomes of a random variable and the corresponding probabilities.

. . .

- Summary that describes the spread of data points in a set
- Essential for making inferences and assumptions from data

. . .

[Key Takeaway:]{.note} The shape of a distribution provides valuable information



---

## Uniform distribution

The probability density function of a variable uniformly distributed between 0 and 2 is

$$
f(x) =
\begin{cases}
  \frac{1}{2} & \text{if } 0 \leq x \leq 2 \\
  0 & \text{otherwise}
\end{cases}
$$

```{R}
#| label: "unif_dist_01"
#| fig-align: center
#| echo: FALSE
#| fig-width: 16

x <- seq(-1, 3, 0.01)
y <- seq(1, 1.5, 0.01)
z <- seq(0, 2 ,0.01)

ggplot() +
  scale_x_continuous(limits = c(-1, 3), expand=c(0,0)) +
  scale_y_continuous(limits = c(0, 1), expand=c(0,0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1)) +
  geom_ribbon(aes(x = z, ymin = 0, ymax = 0.5), fill = "grey85", linetype = "blank") +
  xlab(expression(X)) + 
  ylab("Density") +
  mytheme_s
```

---

## Uniform distribution

By definition, the area under $f(x)$ is equal to 1.

The [shaded area]{.hi} illustrates the probability of the event $1 \leq X \leq 1.5$.

<br>

$$
P(1 \leq X \leq 1.5) = (1.5-1) \times0.5 = 0.25
$$

```{R}
#| label: "unif_dist_02"
#| fig-align: center
#| echo: FALSE
#| fig-width: 16
x <- seq(-1, 3, 0.01)
y <- seq(1, 1.5, 0.01)
z <- seq(0, 2 ,0.01)

ggplot() +
  scale_x_continuous(limits = c(-1, 3), expand=c(0,0)) +
  scale_y_continuous(limits = c(0, 1), expand=c(0,0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1)) +
  geom_ribbon(aes(x = z, ymin = 0, ymax = 0.5), fill = "grey85", linetype = "blank") +
  geom_ribbon(aes(x = y, ymin = 0, ymax = 0.5), fill = hii, linetype = "blank") +
  geom_vline(xintercept = 1, size = 0.35, linetype = "dashed", color = hi) +
  geom_vline(xintercept = 1.5, size = 0.35, linetype = "dashed", color = hi) +
  xlab(expression(X)) + 
  ylab("Density") +
  mytheme_s
```

---

## Normal Distribution

The ["bell curve"]{.hi .note}

- Symmetric: mean and median occur at the same point (_i.e._, no skew).
- Low-probability events in tails; high-probability events near center.

<br>

```{R}
#| label: "normal_dist_01"
#| fig-align: center
#| echo: FALSE
#| fig-width: 16

df <- tibble(x = seq(-4, 4, 0.01), y = dnorm(x)) %>%
  rbind(., tibble(x = seq(4, -4, -0.01), y = 0))

ggplot() +
  scale_x_continuous(limits = c(-4, 4), expand=c(0,0)) +
  scale_y_continuous(limits = c(0, 0.5), expand=c(0,0), breaks = c(0, 0.5), labels = c(0, 0.5)) +
  geom_polygon(data = df, aes(x, y), fill = "grey85") +
  mytheme_s +
  xlab(expression(X)) + 
  ylab("Density")
```

---

## Normal Distribution

The [shaded area]{.hi} illustrates the probability of the event $-2 \leq X \leq 2$.

- "Find area under curve" [=]{.mono} use integral calculus (or, in practice, [R]{.mono}).
$$
P(-2 \leq X \leq 2) \approx 0.95
$$

```{R}
#| label: "normal_dist_02"
#| fig-align: center
#| echo: FALSE
#| fig-width: 16

df <- tibble(x = seq(-4, 4, 0.01), y = dnorm(x)) %>%
  rbind(., tibble(x = seq(4, -4, -0.01), y = 0))
ggplot() +
  scale_x_continuous(limits = c(-4, 4), expand=c(0,0)) +
  scale_y_continuous(limits = c(0, 0.5), expand=c(0,0), breaks = c(0, 0.5), labels = c(0, 0.5)) +
  geom_polygon(data = df, aes(x, y), fill = "grey85") +
  geom_polygon(data = df %>% filter(x <= qnorm(0.5 + 0.475) & x >= qnorm(0.5 - 0.475)), aes(x, y), fill = hii) +
  geom_vline(xintercept = qnorm(0.5 + 0.475), size = 0.35, linetype = "dashed", color = hi) +
  geom_vline(xintercept = qnorm(0.5 - 0.475), size = 0.35, linetype = "dashed", color = hi) +
  mytheme_s +
  xlab(expression(X)) + 
  ylab("Density")
```

---

## Normal Distribution


Continuous distribution where $x_i$ takes the value of any real number (${\mathbb{R}}$)

- Domain spans the entire real line
- Centered on the distribution mean $\mu$

[Rule 1:]{.note} The probability that the random variable takes a value $x_i$ is 0 for any $x_i\in {\mathbb{R}}$

[Rule 2:]{.note} The probability that the random variable falls between $[x_i,x_j]$ range, where $x_i \neq x_j$, is the area under $p(x)$ between those two values 

The area above represents $p(x)=0.95$. The values $\{-1.96, 1.96\}$ represent the 95% confidence interval for $\mu$.